# on:
#   push:
#     branches:
#       - main
# permissions:
#   contents: write
#   pull-requests: write
# name: release-please
# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Log secret
#         run: echo ${{ secrets.GITHUB_TOKEN }}
#       - uses: googleapis/release-please-action@v4
#         with:
#           # Using the default GITHUB_TOKEN which has the required permissions
#           # for release-please to create releases and pull requests
#           token: ${{ secrets.GITHUB_TOKEN }}
#           # this is a built-in strategy in release-please, see "Action Inputs"
#           # for more options
#           release-type: node

name: Release Please

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'

      - name: Generate Changelog & Version
        run: |
          release-please release-pr --token=${{ secrets.GITHUB_TOKEN }}
          git add .
          git commit -m "chore: update CHANGELOG and package.json" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
